import { NextRequest, NextResponse } from 'next/server';
import * as fs from 'fs';
import * as path from 'path';
import axios from 'axios';
import { v4 as uuidv4 } from 'uuid';
import prisma from '@/lib/db';
import { withAdminAuth } from '@/lib/admin-guard';

export async function GET(req: NextRequest) {
  return withAdminAuth(req, async (req) => {
    try {
      const { searchParams } = new URL(req.url);
      const job = searchParams.get('job');
      const gender = searchParams.get('gender');

      const where: any = {};
      if (job) where.job = job;
      if (gender) where.gender = gender;

      const baseImages = await prisma.jobBaseImage.findMany({
        where,
        orderBy: { createdAt: 'desc' },
      });

      return NextResponse.json(baseImages);
    } catch (error: any) {
      console.error('[API] List base images error:', error.message);
      return NextResponse.json({ message: 'Internal server error' }, { status: 500 });
    }
  }, { roles: ['admin'] });
}

export async function POST(req: NextRequest) {
  return withAdminAuth(req, async (req) => {
    try {
      const body = await req.json();
      const { job, gender, imageUrl } = body;

      if (!job?.trim()) {
        return NextResponse.json({ message: 'job is required' }, { status: 400 });
      }
      if (gender !== 'male' && gender !== 'female') {
        return NextResponse.json({ message: 'gender must be "male" or "female"' }, { status: 400 });
      }
      if (!imageUrl?.trim()) {
        return NextResponse.json({ message: 'imageUrl is required' }, { status: 400 });
      }

      // Download the image and store it locally under public/base-images
      let buffer: Buffer;
      let contentType = 'image/png';
      try {
        const res = await axios.get(imageUrl.trim(), {
          responseType: 'arraybuffer',
          timeout: 30_000,
          headers: { 'User-Agent': 'Mozilla/5.0 (compatible; PhotoboothBot/1.0)' },
        });
        buffer = Buffer.from(res.data);
        contentType = String(res.headers['content-type'] || contentType);
      } catch (err: any) {
        return NextResponse.json(
          { message: `Failed to download image from URL: ${err.message}` },
          { status: 400 },
        );
      }

      const extMap: Record<string, string> = {
        'image/jpeg': '.jpg',
        'image/png': '.png',
        'image/webp': '.webp',
        'image/svg+xml': '.svg',
      };
      const ext = extMap[contentType.split(';')[0].trim()] || path.extname(new URL(imageUrl).pathname) || '.png';

      const baseDir = path.join(process.cwd(), 'public', 'base-images');
      if (!fs.existsSync(baseDir)) fs.mkdirSync(baseDir, { recursive: true });

      const filename = `base_${job.trim().toLowerCase().replace(/[^a-z0-9]+/g, '_')}_${gender}_${uuidv4()}${ext}`;
      const filePath = path.join(baseDir, filename);
      fs.writeFileSync(filePath, buffer);

      const servedUrl = `/base-images/${filename}`;

      const baseImage = await prisma.jobBaseImage.create({
        data: {
          job: job.trim(),
          gender,
          imageUrl: servedUrl,
          imagePath: filePath,
          autoGenerated: false,
        },
      });

      return NextResponse.json(baseImage, { status: 201 });
    } catch (error: any) {
      console.error('[API] Create base image error:', error.message);
      return NextResponse.json({ message: 'Internal server error' }, { status: 500 });
    }
  }, { roles: ['admin'] });
}
